# Generated by Django 4.1.7 on 2023-03-29 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_superadmin_account_is_super_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_super_admin',
            new_name='is_superadmin',
        ),
    ]
